version: '3'
services:
  jenkins:
    image: myjenkins-blueocean
    container_name: jenkins-blueocean
    restart: on-failure
    user: root
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/"
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "49000:49000"
      - "3031:3031"
      - "9091:9091"
    networks:
      - jenkins
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - jenkins
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - jenkins
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3030

networks:
  jenkins:
    external: true

volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true
  grafana-data:
    driver: local