version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  build:
    commands:
      - cd react-app
      - npm install
      - npm run build
      - aws s3 sync build s3://mfdsix-006-dcdg-react-app/ --delete